// ─── Site Metadata ───────────────────────────────────────────────────────────
export const SITE = {
  name:        "J&J Tech Solutions Studio",
  tagline:     "Modern Websites & Business Systems for Local Businesses",
  description: "We build websites, POS systems, booking systems, and custom business solutions tailored for Filipino local businesses.",
  email:       "jandjtechsolutions@gmail.com",
  facebook:    "https://www.facebook.com/share/18jCi9b2tp/",
  whatsapp:    "https://wa.me/639XXXXXXXXX", // replace with real number
  messenger:   "https://m.me/jandjtechsolutions",
};

// ─── Navigation Links ────────────────────────────────────────────────────────
export const NAV_LINKS = [
  { label: "Services",      href: "#services"      },
  { label: "Portfolio",     href: "#portfolio"     },
  { label: "Systems",       href: "#systems"       },
  { label: "Testimonials",  href: "#testimonials"  },
  { label: "Reviews",       href: "#reviews"       },
  { label: "About",         href: "#about"         },
  { label: "FAQ",           href: "#faq"           },
  { label: "Contact",       href: "#contact"       },
];

// ─── Services ────────────────────────────────────────────────────────────────
export const SERVICES = [
  {
    id:          "basic-website",
    icon:        "Globe",
    title:       "Basic Website Package",
    description: "Clean, fast, and mobile-ready websites. Perfect for establishing your online presence with a professional look.",
    targets:     ["Sari-sari store", "Freelancers", "Small shops", "Startups"],
    price:       "Starting at ₱3,500",
    color:       "blue",
  },
  {
    id:          "business-website",
    icon:        "LayoutDashboard",
    title:       "Business Website + Menu System",
    description: "A full business website with a digital menu or product catalog that you can update anytime — no coding needed.",
    targets:     ["Restaurants", "Cafes", "Food stalls", "Bakeries"],
    price:       "Starting at ₱7,500",
    color:       "amber",
  },
  {
    id:          "booking-system",
    icon:        "CalendarCheck",
    title:       "Booking / Ordering System",
    description: "Let customers book appointments or place orders online 24/7. Reduce no-shows and streamline your operations.",
    targets:     ["Salons", "Clinics", "Repair shops", "Event services"],
    price:       "Starting at ₱12,000",
    color:       "blue",
  },
  {
    id:          "custom-system",
    icon:        "Cpu",
    title:       "Custom Business Systems",
    description: "POS, inventory management, employee dashboards, and reporting systems built exactly for your workflow.",
    targets:     ["Hardware stores", "Groceries", "LGUs", "Medium businesses"],
    price:       "Starting at ₱18,000",
    color:       "amber",
  },
  {
    id:          "industry-solution",
    icon:        "Store",
    title:       "Industry Solutions",
    description: "Ready-made templates adapted for your industry — coffee shops, gyms, salons, hardware, and more.",
    targets:     ["Coffee shops", "Gyms", "Salons", "Hardware stores"],
    price:       "Starting at ₱9,500",
    color:       "blue",
  },
];

// ─── Portfolio Projects ──────────────────────────────────────────────────────
export type PortfolioProject = {
  id:          string;
  title:       string;
  category:    string;
  categoryColor: string;   // tailwind bg color class for badge
  description: string;
  longDesc:    string;
  tech:        { label: string; color: string }[];
  screenshot:  string;     // path under /portfolio/
  demoUrl:     string;     // "#" if no live demo
  accentColor: string;     // hex for glow + badge
  bgColor:     string;     // dark bg for preview card
  emoji:       string;
  features:    string[];
  client:      string;
  year:        string;
  status:      "Live" | "Demo" | "Client" | "Academic";
};

export const PORTFOLIO: PortfolioProject[] = [
  {
    id:          "brew-haven",
    title:       "Brew Haven Coffee Shop",
    category:    "Business Website",
    categoryColor: "bg-amber-500/20 text-amber-400 border-amber-500/30",
    description: "Modern coffee shop website with digital menu, online ordering, and specialty coffee branding.",
    longDesc:    "A full editorial coffee shop website built with Next.js and Supabase. Features a dynamic digital menu, online ordering flow, loyalty section, and a warm dark brown aesthetic that captures the specialty coffee experience. Deployed live on Vercel.",
    tech: [
      { label: "Next.js 14",      color: "#ffffff" },
      { label: "Tailwind CSS",    color: "#38bdf8" },
      { label: "Supabase",        color: "#3ECF8E" },
      { label: "Framer Motion",   color: "#a855f7" },
      { label: "Vercel",          color: "#ffffff" },
    ],
    screenshot:  "/portfolio/heaven-brew.png",
    demoUrl:     "https://brew-haven-coffee-shop-lyart.vercel.app/",
    accentColor: "#F59E0B",
    bgColor:     "#1a1200",
    emoji:       "☕",
    features:    ["Digital menu with categories", "Online ordering flow", "Dark editorial design", "Mobile-first responsive", "Live on Vercel"],
    client:      "Demo / Portfolio",
    year:        "2026",
    status:      "Live",
  },
  {
    id:          "review-hub",
    title:       "ReviewHub PH",
    category:    "SaaS Platform",
    categoryColor: "bg-violet-500/20 text-violet-400 border-violet-500/30",
    description: "AI-powered online reviewer for Filipino board exam takers — timed quizzes, study plans, and progress tracking.",
    longDesc:    "A free, AI-powered review platform built specifically for Filipino students preparing for board exams. Features timed mock exams, an AI study plan generator powered by OpenAI, detailed analytics and progress dashboards, and subject-specific reviewers. Built with Next.js 14 App Router and Supabase for real-time data.",
    tech: [
      { label: "Next.js 14",   color: "#ffffff" },
      { label: "Supabase",     color: "#3ECF8E" },
      { label: "OpenAI API",   color: "#10a37f" },
      { label: "Tailwind CSS", color: "#38bdf8" },
      { label: "TypeScript",   color: "#3178c6" },
    ],
    screenshot:  "/portfolio/review-hub.png",
    demoUrl:     "#",
    accentColor: "#7C3AED",
    bgColor:     "#0d0022",
    emoji:       "📚",
    features:    ["AI-generated study plans", "Timed quiz engine", "Board exam categories", "Progress tracking dashboard", "Free for Filipino students"],
    client:      "Demo / Portfolio",
    year:        "2026",
    status:      "Demo",
  },
  {
    id:          "apostolic-vicariate",
    title:       "Apostolic Vicariate of San Jose",
    category:    "Parish Service Platform",
    categoryColor: "bg-yellow-500/20 text-yellow-400 border-yellow-500/30",
    description: "Full parish service portal for sacrament applications, event management, and faith community engagement.",
    longDesc:    "A comprehensive digital platform for the Apostolic Vicariate of San Jose that allows parishioners to apply for sacraments online, track request status, register for events, and engage with the parish community. Built with pure PHP and Bootstrap, featuring a sacred editorial design with dark navy and gold tones. Includes an admin panel for parish staff.",
    tech: [
      { label: "PHP (Pure)",    color: "#8892BF" },
      { label: "Bootstrap 5",  color: "#7952b3" },
      { label: "MySQL",        color: "#4479A1" },
      { label: "JavaScript",   color: "#f7df1e" },
      { label: "CSS3",         color: "#264de4" },
    ],
    screenshot:  "/portfolio/apostolic-vicariate.png",
    demoUrl:     "https://vicarparishservice.com/",
    accentColor: "#C9A84C",
    bgColor:     "#0a0e1a",
    emoji:       "⛪",
    features:    ["Sacrament request system", "Event registration", "Parish announcements", "Admin management panel", "Sacred editorial UI"],
    client:      "Apostolic Vicariate of San Jose",
    year:        "2026",
    status:      "Client",
  },
  {
    id:          "mysp-ecommerce",
    title:       "MYSP — Make Yourself Proud",
    category:    "E-Commerce Store",
    categoryColor: "bg-yellow-500/20 text-yellow-400 border-yellow-500/30",
    description: "Premium streetwear e-commerce store with product catalog, cart system, and editorial brand experience.",
    longDesc:    "A full-featured e-commerce platform for MYSP, a Philippine streetwear brand. Built with Laravel 12, the store features a dark editorial aesthetic with gold accents, product catalog with Men/Women categories, shopping cart, search functionality, and a login/register system. Designed to reflect the brand's 'Make Yourself Proud' identity.",
    tech: [
      { label: "Laravel 12",   color: "#FF2D20" },
      { label: "Tailwind CSS", color: "#38bdf8" },
      { label: "MySQL",        color: "#4479A1" },
      { label: "Alpine.js",    color: "#77c1d2" },
      { label: "Blade",        color: "#FF2D20" },
    ],
    screenshot:  "/portfolio/mysp-ecommerce.jpg",
    demoUrl:     "https://darkgreen-stork-334679.hostingersite.com/",
    accentColor: "#D4A017",
    bgColor:     "#0a0a0a",
    emoji:       "",
    features:    ["Product catalog (Men/Women)", "Shopping cart & checkout", "User authentication", "Search & filter", "Dark editorial design"],
    client:      "MYSP Clothing Brand",
    year:        "2026",
    status:      "Client",
  },
  {
    id:          "vitality-fitness",
    title:       "Vitality Fitness Center",
    category:    "Business Website",
    categoryColor: "bg-green-500/20 text-green-400 border-green-500/30",
    description: "High-energy gym website with membership plans, trainer profiles, class schedules, and a live booking system.",
    longDesc:    "A bold, high-impact fitness center website for Vitality Fitness Center. Features a dark gym aesthetic with neon green accents, live class schedule widget, membership plan cards, trainer profiles, WhatsApp/Messenger floating CTAs, and a sign-up flow. Built with PHP, Bootstrap, and MySQL, deployed on Hostinger.",
    tech: [
      { label: "PHP",          color: "#8892BF" },
      { label: "MySQL",        color: "#4479A1" },
      { label: "Bootstrap 5",  color: "#7952b3" },
      { label: "JavaScript",   color: "#f7df1e" },
      { label: "Hostinger",    color: "#673de6" },
    ],
    screenshot:  "/portfolio/vitality-fitness.png",
    demoUrl:     "https://darkslategray-jackal-727170.hostingersite.com/#",
    accentColor: "#84cc16",
    bgColor:     "#0a1a00",
    emoji:       "",
    features:    ["Membership plan section", "Class schedule widget", "Trainer profiles", "WhatsApp / Messenger CTA", "Live on Hostinger"],
    client:      "Vitality Fitness Center",
    year:        "2026",
    status:      "Live",
  },
  {
    id:          "crimetrack-cms",
    title:       "CrimeTrack CMS",
    category:    "Law Enforcement System",
    categoryColor: "bg-yellow-500/20 text-yellow-400 border-yellow-500/30",
    description: "Web-based crime case management system with interactive crime mapping for a Philippine police station.",
    longDesc:    "A secure web-based case management system developed for the San Jose Philippines National Police. Features interactive crime mapping using Leaflet.js and OpenStreetMap, case filing and tracking, incident reporting, role-based access control, and DOH-format report generation. This was also the core of an undergraduate research paper (Chapters 1–3). Built entirely in vanilla PHP with MySQL.",
    tech: [
      { label: "PHP (Vanilla)", color: "#8892BF" },
      { label: "MySQL",         color: "#4479A1" },
      { label: "Leaflet.js",    color: "#199900" },
      { label: "OpenStreetMap", color: "#7EBC6F" },
      { label: "Bootstrap 5",   color: "#7952b3" },
    ],
    screenshot:  "/portfolio/crimetrack.jpg",
    demoUrl:     "https://lemonchiffon-caribou-974307.hostingersite.com/loading.html",
    accentColor: "#EAB308",
    bgColor:     "#0a0f00",
    emoji:       "",
    features:    ["Interactive crime map (Leaflet.js)", "Case filing & status tracking", "Incident reporting module", "Role-based access (6 roles)", "Undergraduate research project"],
    client:      "San Jose PNP / Academic Research",
    year:        "2025",
    status:      "Academic",
  },
  {
    id:          "southern-mega-steel",
    title:       "Southern Mega Steel Enterprise",
    category:    "Corporate Website",
    categoryColor: "bg-red-500/20 text-red-400 border-red-500/30",
    description: "Professional corporate website for an established steel trading company in Bacoor, Cavite — Est. 1996.",
    longDesc:    "A full editorial corporate website for Southern Mega Steel Trading Enterprise Inc., a steel supplier established in 1996 in Bacoor, Cavite. Built with Laravel 11, Blade, Tailwind CSS, and Alpine.js with a Filament v3 admin panel for content management. Features a bold red industrial design, product catalog, services section, contact form with email integration, and WhatsApp/Messenger floating buttons. Deployed on Hostinger.",
    tech: [
      { label: "Laravel 11",   color: "#FF2D20" },
      { label: "Tailwind CSS", color: "#38bdf8" },
      { label: "Filament v3",  color: "#f59e0b" },
      { label: "Alpine.js",    color: "#77c1d2" },
      { label: "MySQL",        color: "#4479A1" },
    ],
    screenshot:  "/portfolio/southern-mega-steel.jpg",
    demoUrl:     "https://darkseagreen-jackal-250287.hostingersite.com/",
    accentColor: "#EF4444",
    bgColor:     "#1a0000",
    emoji:       "",
    features:    ["Product & services catalog", "Filament v3 admin panel", "Email inquiry integration", "WhatsApp / Messenger CTA", "Corporate editorial design"],
    client:      "Southern Mega Steel Trading Enterprise",
    year:        "2026",
    status:      "Client",
  },
  {
    id:          "aidtrack",
    title:       "AidTrack — Financial Aid System",
    category:    "Government System",
    categoryColor: "bg-orange-500/20 text-orange-400 border-orange-500/30",
    description: "Financial aid tracking system for a Congressman's Office — from request submission to approval and fund release.",
    longDesc:    "AidTrack is an official financial assistance management system developed for a Congressman's Office in the Philippines. It streamlines every step from citizen request submission and document verification to staff approval workflows and fund release tracking. The dark navy dashboard shows real-time stats (1,248 total requests, 867 approved, 142 pending), assistance by category (Medical 78%, Burial 45%), and recent requests. Built with pure PHP, featuring a polished dark orange UI.",
    tech: [
      { label: "PHP (Pure)",  color: "#8892BF" },
      { label: "MySQL",       color: "#4479A1" },
      { label: "Bootstrap 5", color: "#7952b3" },
      { label: "JavaScript",  color: "#f7df1e" },
      { label: "Chart.js",    color: "#FF6384" },
    ],
    screenshot:  "/portfolio/aidtrack.png",
    demoUrl:     "https://lightsteelblue-partridge-787193.hostingersite.com/",
    accentColor: "#F97316",
    bgColor:     "#0d1117",
    emoji:       "",
    features:    ["Request submission portal", "Document verification workflow", "Approval & fund release tracking", "Real-time analytics dashboard", "Official government deployment"],
    client:      "Congressman's Office (Philippines)",
    year:        "2026",
    status:      "Client",
  },
  {
    id:          "san-jose-market",
    title:       "San Jose Public Market — RPMS",
    category:    "Payment Management System",
    categoryColor: "bg-blue-500/20 text-blue-400 border-blue-500/30",
    description: "Rental Public Market System for automated stall rental tracking, billing, and payment management.",
    longDesc:    "The Rental Public Market System (RPMS) is a web-based solution for the San Jose Public Market covering stall registration, rental billing, payment recording, delinquency tracking, and official receipt generation. Built as an academic final project using ASP.NET Web Forms with a clean admin interface. Completed under a crash build timeline with a May 2026 deadline.",
    tech: [
      { label: "ASP.NET Web Forms", color: "#512BD4" },
      { label: "C#",                color: "#239120" },
      { label: "SQL Server",        color: "#CC2927" },
      { label: "Bootstrap 5",       color: "#7952b3" },
      { label: ".NET Framework",    color: "#512BD4" },
    ],
    screenshot:  "/portfolio/rpms.png",
    demoUrl:     "https://yellowgreen-gaur-925276.hostingersite.com/",
    accentColor: "#3B82F6",
    bgColor:     "#001133",
    emoji:       "",
    features:    ["Stall registration & management", "Rental billing & invoicing", "Payment recording & receipts", "Delinquency tracking", "Academic final project (ASP.NET)"],
    client:      "Academic Final Project",
    year:        "2026",
    status:      "Academic",
  },
  {
    id:          "calintaan-triskelion",
    title:       "Calintaan Triskelions Portal",
    category:    "Community Portal",
    categoryColor: "bg-yellow-500/20 text-yellow-400 border-yellow-500/30",
    description: "Digital registration and information portal for the Tau Gamma Phi Calintaan chapter — Occidental Mindoro.",
    longDesc:    "A full-featured fraternity digital portal for Calintaan Triskelions (Tau Gamma Phi — Calintaan Municipal Grand Council). Built with vanilla PHP and JavaScript, the system supports two registration flows: Incoming Member and Brod Self-Registration. Features chapter management, event calendars, announcements, and a secure login portal. The black and gold design reflects the fraternity's identity. 'Fortis Voluntas Fraternitas' — Since 2007.",
    tech: [
      { label: "PHP (Vanilla)", color: "#8892BF" },
      { label: "MySQL",         color: "#4479A1" },
      { label: "JavaScript",    color: "#f7df1e" },
      { label: "CSS3",          color: "#264de4" },
      { label: "Bootstrap 5",   color: "#7952b3" },
    ],
    screenshot:  "/portfolio/calintaan-triskelion.png",
    demoUrl:     "https://calintaantriskelions.com",
    accentColor: "#EAB308",
    bgColor:     "#0a0800",
    emoji:       "",
    features:    ["Incoming member registration", "Brod self-registration flow", "Chapter & events management", "Announcements board", "Black & gold fraternity branding"],
    client:      "Calintaan Triskelions — Tau Gamma Phi",
    year:        "2026",
    status:      "Client",
  },
  {
    id:          "tesda-occ-mindoro",
    title:       "TESDA Occidental Mindoro",
    category:    "Government Web Portal",
    categoryColor: "bg-blue-500/20 text-blue-400 border-blue-500/30",
    description: "Official TESDA provincial portal with program listings, appointment booking, graduate tracking, and certification verification.",
    longDesc:    "An official web portal for TESDA Occidental Mindoro built with Angular and Firebase. Features a comprehensive programs & services directory, online appointment booking, graduate tracking dashboard, certification verification, contact management, and a transparency section. The live system shows 50+ programs, 10K+ graduates, and 95% employment rate. Developed using Angular SPA architecture with Firebase Realtime Database and Tailwind CSS.",
    tech: [
      { label: "Angular",        color: "#DD0031" },
      { label: "Firebase",       color: "#FFCA28" },
      { label: "Tailwind CSS",   color: "#38bdf8" },
      { label: "TypeScript",     color: "#3178c6" },
      { label: "Firestore",      color: "#FFCA28" },
    ],
    screenshot:  "/portfolio/tesda.png",
    demoUrl:     "https://tesda-system.web.app/landing-page/home",
    accentColor: "#3B82F6",
    bgColor:     "#001020",
    emoji:       "🎓",
    features:    ["Programs & services directory", "Online appointment booking", "Graduate tracking", "Certification verification", "Angular SPA + Firebase live deployment"],
    client:      "TESDA Occidental Mindoro",
    year:        "2025",
    status:      "Live",
  },
  {
    id:          "medtrack",
    title:       "MedTrack — PDL Health System",
    category:    "Healthcare System",
    categoryColor: "bg-emerald-500/20 text-emerald-400 border-emerald-500/30",
    description: "Centralized health monitoring system for Persons Deprived of Liberty (PDL) at San Jose District Jail.",
    longDesc:    "MedTrack is a full-stack health monitoring system for managing PDL (Persons Deprived of Liberty) medical records at San Jose District Jail, under the Bureau of Jail Management and Penology (BJMP). Features patient health records, consultation calendar, medications inventory, real-time monitoring, and role-based access. Built with Python Django and SQLite, containerized with Docker and deployed on a Hostinger VPS via Docker Compose with Nginx and Gunicorn.",
    tech: [
      { label: "Python Django", color: "#092E20" },
      { label: "SQLite",        color: "#003B57" },
      { label: "Docker",        color: "#2496ED" },
      { label: "Nginx",         color: "#009900" },
      { label: "Hostinger VPS", color: "#673de6" },
    ],
    screenshot:  "/portfolio/medtrack.png",
    demoUrl:     "http://srv1474157.hstgr.cloud/",
    accentColor: "#10B981",
    bgColor:     "#001a10",
    emoji:       "🏥",
    features:    ["PDL health records management", "Consultation calendar", "Medications & inventory", "Docker + VPS deployment", "BJMP-compliant access control"],
    client:      "San Jose District Jail — BJMP",
    year:        "2025",
    status:      "Client",
  },
  {
    id:          "calintaan-tourism",
    title:       "Discover Calintaan Tourism",
    category:    "Tourism Website",
    categoryColor: "bg-green-500/20 text-green-400 border-green-500/30",
    description: "Official tourism portal for Calintaan, Occidental Mindoro — eco-tourism, beach resorts, agritourism, and local culture.",
    longDesc:    "The official tourism website for the Municipality of Calintaan, Occidental Mindoro — developed for the LGU Calintaan Tourism Office. Built with pure vanilla PHP, CSS, and Bootstrap. Features a mega dropdown navigation covering Agritourism, Ecotourism, Attractions, Beach Resorts, Hotels, and Resorts. Includes a search system, stay & eat listings, cultural content, an e-shop, and a built-in chatbot. Also highlights the Tau-Buhid Mangyan indigenous community as a key cultural tourism element. Deployed on calintaan.com.",
    tech: [
      { label: "PHP (Vanilla)", color: "#8892BF" },
      { label: "CSS3",          color: "#264de4" },
      { label: "Bootstrap 5",   color: "#7952b3" },
      { label: "JavaScript",    color: "#f7df1e" },
      { label: "MySQL",         color: "#4479A1" },
    ],
    screenshot:  "/portfolio/calintaan-tourism.png",
    demoUrl:     "https://calintaan.com",
    accentColor: "#22c55e",
    bgColor:     "#001a08",
    emoji:       "🏝️",
    features:    ["Mega dropdown tour categories", "Search & filter system", "Stay & Eat listings", "E-shop for local products", "LGU official deployment — calintaan.com"],
    client:      "LGU Calintaan Tourism Office",
    year:        "2024",
    status:      "Live",
  },
  // ── NEW ENTRY ─────────────────────────────────────────────────────────────
  {
    id:          "farmventure-2d",
    title:       "FarmVenture — 2D Farming Game",
    category:    "2D Game",
    categoryColor: "bg-lime-500/20 text-lime-400 border-lime-500/30",
    description: "A top-down 2D farming adventure game with crop planting, tool mechanics, a timed challenge system, and charming pixel-art-style visuals.",
    longDesc:    "FarmVenture is a top-down 2D farming and exploration game built from scratch. Players manage their farm by planting seeds, watering crops, and harvesting produce within a timed challenge system. The game features a character with animated movement, a hotbar inventory system (axe, watering can, basket, seeds), directional signposts, ambient farm scenery, and a coin economy. Designed with a bright, hand-painted art style reminiscent of mobile farming RPGs. Available as a downloadable desktop build.",
    tech: [
      { label: "Unity",          color: "#ffffff" },
      { label: "C#",             color: "#239120" },
      { label: "2D Tilemap",     color: "#f59e0b" },
      { label: "Sprite Atlas",   color: "#38bdf8" },
      { label: "Game Build",     color: "#a855f7" },
    ],
    screenshot:  "/portfolio/farmventure-2d.jpg",
    demoUrl:     "https://drive.google.com/file/d/1ev6SqF7qNY0GdpQCxTlhY9_2notvxd0b/view?usp=sharing",
    accentColor: "#84cc16",
    bgColor:     "#0a1a00",
    emoji:       "🌾",
    features:    ["Top-down 2D farming gameplay", "Timed challenge system", "Hotbar inventory (tools & seeds)", "Coin economy & progression", "Downloadable desktop build"],
    client:      "Demo / Portfolio",
    year:        "2026",
    status:      "Demo",
  },
 // ── NEW ENTRY ─────────────────────────────────────────────────────────────
  {
    id:          "alertbites",
    title:       "AlertBites — Rabies Awareness App",
    category:    "Mobile Application",
    categoryColor: "bg-green-500/20 text-green-400 border-green-500/30",
    description: "A rabies awareness mobile app with bite incident reporting, prevention guides, and real-time risk alerts — powered by the Rabies Prevention Initiative.",
    longDesc:    "AlertBites is a mobile application built under the Rabies Prevention Initiative with the mission: 'Know the risks. Stay protected.' The app features a sleek dark-green splash screen with an animated loading sequence, rabies awareness content, bite incident tracking, prevention and first-aid guides, and community alert features. Designed for public health awareness, the app targets at-risk communities in the Philippines and is distributed as an Android APK. The branding combines a paw-heart logo with bold typography to signal urgency while remaining approachable.",
    tech: [
      { label: "Flutter",        color: "#54C5F8" },
      { label: "Dart",           color: "#0175C2" },
      { label: "Firebase",       color: "#FFCA28" },
      { label: "Android APK",    color: "#3DDC84" },
      { label: "Google Drive",   color: "#4285F4" },
    ],
    screenshot:  "/portfolio/alertbites.jpg",
    demoUrl:     "https://drive.google.com/file/d/10I8l9OMX3Jv-c8ZOWfi20tWuzknxV1hD/view",
    accentColor: "#22c55e",
    bgColor:     "#001a08",
    emoji:       "🐾",
    features:    ["Rabies awareness & prevention info", "Bite incident reporting", "Animated splash & loading screen", "Public health alert system", "Android APK distribution"],
    client:      "Rabies Prevention Initiative",
    year:        "2026",
    status:      "Demo",
  },
 
  // ── NEW ENTRY ─────────────────────────────────────────────────────────────
  {
    id:          "bubog-health-center",
    title:       "Barangay Bubog Health Center",
    category:    "Healthcare Web Portal",
    categoryColor: "bg-teal-500/20 text-teal-400 border-teal-500/30",
    description: "Community health portal for Barangay Bubog, San Jose, Occidental Mindoro — patient registration, health services, and barangay health programs.",
    longDesc:    "A full-featured barangay health center web portal for Barangay Bubog Health Station / Birthing Facility in San Jose, Occidental Mindoro. The system provides patient registration and login, walk-in appointment scheduling, vaccination drive announcements, pre-natal care scheduling, and a dedicated 4Ps (Pantawid Pamilyang Pilipino Program) health assessment module. The dashboard displays live stats: 248 registered patients, 6 health services, and 14 medical staff. Built with pure PHP and MySQL featuring a dark teal editorial design.",
    tech: [
      { label: "PHP (Pure)",   color: "#8892BF" },
      { label: "MySQL",        color: "#4479A1" },
      { label: "Bootstrap 5",  color: "#7952b3" },
      { label: "JavaScript",   color: "#f7df1e" },
      { label: "CSS3",         color: "#264de4" },
    ],
    screenshot:  "/portfolio/bubog-health-center.jpg",
    demoUrl:     "https://red-jay-613692.hostingersite.com/",
    accentColor: "#14b8a6",
    bgColor:     "#001a15",
    emoji:       "🏥",
    features:    ["Patient registration & login", "Walk-in appointment scheduling", "Vaccination drive module", "Pre-natal care scheduling", "4Ps health program section"],
    client:      "Barangay Bubog Health Station — San Jose, Occidental Mindoro",
    year:        "2026",
    status:      "Client",
  },
];
 

// ─── Buy/Customize Packages ──────────────────────────────────────────────────
export const SYSTEMS = [
  {
    id:       "ready-website",
    name:     "Website",
    popular:  false,
    buyPrice: "₱3,500",
    customPrice: "Request Quote",
    delivery: { buy: "3–5 days", custom: "7–14 days" },
    buyFeatures: [
      "5-page website (Home, About, Services, Gallery, Contact)",
      "Mobile-responsive design",
      "Contact form with email notification",
      "Basic SEO setup",
      "1 round of revisions",
      "1 month free support",
    ],
    customFeatures: [
      "Unlimited pages & sections",
      "Custom design matching your brand",
      "CMS for easy content updates",
      "Advanced SEO + performance",
      "Integrations (Maps, Booking, Chat)",
      "3 months support + training",
    ],
  },
  {
    id:       "pos-system",
    name:     "POS System",
    popular:  true,
    buyPrice: "₱18,000",
    customPrice: "Request Quote",
    delivery: { buy: "5–7 days", custom: "14–30 days" },
    buyFeatures: [
      "Product & category management",
      "Sales transaction & receipts",
      "Daily/weekly sales reports",
      "User roles (cashier, admin)",
      "Offline-capable (local install)",
      "2 months free support",
    ],
    customFeatures: [
      "Fully tailored to your workflow",
      "Custom modules & integrations",
      "Cloud or local deployment",
      "Multi-branch / multi-user support",
      "API integrations (SMS, payments)",
      "6 months support + training",
    ],
  },
  {
    id:       "booking-system",
    name:     "Booking System",
    popular:  false,
    buyPrice: "₱12,000",
    customPrice: "Request Quote",
    delivery: { buy: "5–7 days", custom: "14–21 days" },
    buyFeatures: [
      "Online appointment booking",
      "Calendar view for staff",
      "Email/SMS confirmations",
      "Customer management",
      "No-show reduction tools",
      "1 month free support",
    ],
    customFeatures: [
      "Multi-service & multi-staff support",
      "Custom booking flows",
      "Payment gateway integration",
      "Automated reminders",
      "Analytics & reporting",
      "3 months support + training",
    ],
  },
];
// ─── Testimonials ────────────────────────────────────────────────────────────
export const TESTIMONIALS = [
  {
    name:     "Maria Santos",
    business: "Brew & Bloom Café, Calapan City",
    quote:    "J&J built our website in less than a week. Grabe ang ganda at ang dali pang i-update ng menu namin. Recommended talaga!",
    rating:   5,
  },
  {
    name:     "Ronnie dela Cruz",
    business: "RC Hardware, San Jose OCC",
    quote:    "Yung POS system nila is super smooth. Mas mabilis na yung checkout namin at may sales report na kami every day.",
    rating:   5,
  },
  {
    name:     "Jenny Ocampo",
    business: "Glam Studio, Mamburao",
    quote:    "Hindi ko inakala na may makaka-build ng ganito ka-professional na booking system sa presyo nila. Sobrang sulit!",
    rating:   5,
  },
];

// ─── FAQs ────────────────────────────────────────────────────────────────────
export const FAQS = [
  {
    q: "Magkano ang typical na project nyo?",
    a: "Depende sa scope. Basic websites start at ₱3,500, while full custom systems start at ₱18,000. We always give a free quote before any commitment.",
  },
  {
    q: "Gaano katagal ang development?",
    a: "Simple websites take 3–5 days. Full business systems typically take 2–4 weeks depending on complexity.",
  },
  {
    q: "Kaya ba nyo mag-host sa Hostinger or InfinityFree?",
    a: "Yes! We can deploy to any hosting provider — Hostinger, InfinityFree, Vercel, or your preferred setup.",
  },
  {
    q: "May after-sales support ba kayo?",
    a: "Lahat ng packages may kasama na support period. We also offer monthly maintenance plans.",
  },
  {
    q: "Puwede ba mag-request ng demo before buying?",
    a: "Absolutely. Just fill out the contact form and we'll set up a live demo walkthrough for you.",
  },
];

// ─── Budget Ranges (for Contact Form) ────────────────────────────────────────
export const BUDGET_RANGES = [
  "Below ₱5,000",
  "₱5,000 – ₱10,000",
  "₱10,000 – ₱20,000",
  "₱20,000 – ₱50,000",
  "₱50,000+",
  "Not sure yet",
];

export const SERVICE_OPTIONS = [
  "Basic Website Package",
  "Business Website + Menu System",
  "Booking / Ordering System",
  "Custom Business System (POS, Inventory)",
  "Industry Solution (Coffee shop, Salon, etc.)",
  "Not sure — I need advice",
];